import { MANAGE_AGENT_INSTRUCTION_SECTIONS } from "../constants/prompts";

const joinSections = (...parts: string[]) => parts.join("\n\n");

export const manageAgentPrompt = joinSections(
  MANAGE_AGENT_INSTRUCTION_SECTIONS.ROLE,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.TOOL_DISPATCH,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_BROWSE,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_FIND,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_DETAIL,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_BOOK,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_LIST,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_CANCEL,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.WORKFLOW_MODIFY,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.TOOL_RESULTS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.SCOPE_BOUNDARY,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.BUSINESS_CONSTRAINTS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.ERROR_HANDLING,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.CONVERSATION_RULES,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.SUGGESTED_ACTIONS,
);
