import { HOMESTAY_AGENT_CONTEXT_PROMPT_SECTION } from "@repo/constants";
import {
  MANAGE_AGENT_INSTRUCTION_SECTIONS,
  MANAGE_AGENT_PLAYBOOK_SECTIONS,
} from "../constants/prompts/intent-playbook";


const joinSections = (...parts: string[]) => parts.join("\n\n");

/**
 * Assembles the homestay-assistant system prompt from the intent playbook.
 * Section order is golden — do not reorder without a regression pass.
 */
export const homestayAssistantPrompt = joinSections(
  MANAGE_AGENT_INSTRUCTION_SECTIONS.ROLE,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.CORE_PRINCIPLES,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.LANGUAGE,
  HOMESTAY_AGENT_CONTEXT_PROMPT_SECTION,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.BOUNDARY,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.PRIORITY_TRIGGERS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.TOOL_DISPATCH,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.ROUTING_RULES,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.BROWSE,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.FIND,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.RECOMMEND,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.DETAIL,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.BOOK,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.LIST,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.CANCEL,
  MANAGE_AGENT_PLAYBOOK_SECTIONS.MODIFY,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.GENERIC_UI_RENDERING,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.TOOL_RESULTS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.RESPOND_GREETINGS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.SCOPE_BOUNDARY,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.BUSINESS_CONSTRAINTS,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.ERROR_HANDLING,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.CONVERSATION_RULES,
  MANAGE_AGENT_INSTRUCTION_SECTIONS.SUGGESTED_ACTIONS,
);
