import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CopilotKitProvider } from "@copilotkit/react-core/v2";
// import { myCustomTheme, Theme } from "@copilotkit/a2ui-renderer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CopilotKitProvider
          runtimeUrl="/api/copilotkit"
          // a2ui={{ theme: "light" as Theme }}
        >{children}</CopilotKitProvider>
      </body>
    </html>
  );
}
