# -------------------------
# Stage 1 - Prune
# -------------------------
  FROM node:22-alpine AS pruner

  WORKDIR /repo
  
  RUN corepack enable
  
  COPY . .
  
  RUN pnpm dlx turbo prune api --docker
  
  # -------------------------
  # Stage 2 - Install + Build
  # -------------------------
  FROM node:22-alpine AS builder
  
  WORKDIR /repo
  
  RUN corepack enable
  
  COPY --from=pruner /repo/out/json/ .
  
  RUN pnpm install --frozen-lockfile
  
  COPY --from=pruner /repo/out/full/ .
  
  RUN pnpm turbo run build --filter=api
  
  # -------------------------
  # Stage 3 - Runtime
  # -------------------------
  FROM node:22-alpine AS runner
  
  WORKDIR /repo
  
  ENV NODE_ENV=production
  
  RUN corepack enable
  
  COPY --from=builder /repo .
  
  WORKDIR /repo/apps/api
  
  EXPOSE 5001
  
  CMD ["node", "dist/main.js"]