FROM node:22-alpine

WORKDIR /repo

RUN corepack enable

COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY turbo.json .

COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile

RUN pnpm turbo run build --filter=api

WORKDIR /repo/apps/api

EXPOSE 5001

CMD ["pnpm", "start:prod"]