packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@scarf/scarf': false
  autoevals: false
  better-sqlite3: set this to true or false
  esbuild: false
  sharp: false
  unrs-resolver: false
overrides:
  "typeorm>better-sqlite3": "-"
