packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@scarf/scarf': true
  better-sqlite3: true
  esbuild: false
  sharp: false
  unrs-resolver: false
patchedDependencies:
  '@mastra/deployer@1.43.0': patches/@mastra__deployer@1.43.0.patch
